name: bump_deps

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  bump_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Setup Yarn
        run: corepack enable && corepack prepare yarn@3.4.1 --activate
      - run: |
          yarn up '*'
          yarn install --mode update-lockfile

      - run: git fetch && git reset --hard origin/main
        working-directory: tavern_helper

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '[bot] Bump deps'
