name: bump_deps

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  bump_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Update package and lock
        run: |
          pnpm update
          rm -rf node_modules
          corepack enable
          corepack prepare yarn@3.4.1 --activate
          yarn up '*'
          yarn install --mode=update-lockfile

      - run: |-
          rm -rf @types
          mkdir -p @types
          wget https://gitlab.com/novi028/JS-Slash-Runner/-/raw/main/dist/@types.zip -O @types.zip
          tar -xf @types.zip -C @types
          rm -f @types.zip
        shell: bash

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '[bot] Bump deps'
